In [1]:
# First in class project

In [2]:
#1
#Import NumPy as np

In [3]:
import numpy as np

In [4]:
#2 
#Create an array of 10 zeros

In [7]:
arr0 = np.zeros(10)
arr0

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
#3
#Create an array of 10 ones
arr1 = np.ones(10)
arr1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [10]:
#4
#Create an array of 10 fives

In [11]:
arr5 = arr1 * 5
arr5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [12]:
#5
#Create an array of integers from 10-50

In [14]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [15]:
#6
#Create an array of even integers from 10-50

In [16]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [17]:
#7
#Create a 3x3 matrix with values ranging from 0-8

In [18]:
arrq7 = np.arange(0,9)

In [19]:
arrq7.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [20]:
#8
#Use NumPy to generate a random number between 0-1

In [21]:
np.random.rand(1)

array([0.05534913])

In [22]:
#9
#Create a matrix using the following statements and display it:
#mat = np.arange(1,26).reshape(5,5)
#mat

In [23]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [24]:
#10a
#Get the sum of all the values in the mat matrix

In [25]:
np.sum(mat)

325

In [26]:
#10b
#Get the standard deviation of the values in the mat matrix

In [27]:
np.std(mat)

7.211102550927978

In [28]:
#10c
#Create a new matrix of 25 ones named mat1

In [29]:
mat1 = np.ones(25).reshape(5,5)
mat1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [30]:
#10d
# Add the values of mat to those of mat1

In [31]:
mat + mat1

array([[ 2.,  3.,  4.,  5.,  6.],
       [ 7.,  8.,  9., 10., 11.],
       [12., 13., 14., 15., 16.],
       [17., 18., 19., 20., 21.],
       [22., 23., 24., 25., 26.]])

In [32]:
#10e
#Multiply the values of mat to those of mat1

In [33]:
mat * mat1

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20.],
       [21., 22., 23., 24., 25.]])

In [ ]:
# Finished